config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :api, default: {format: :json} do
    namespace :v1,  default: {format: :json} do
       post 'login', to: 'authentication#authenticate'
       post 'register', to: 'users#create'
       resources :users do
         resources :posts, only: [:index, :show, :create] do
           resources :comments, only: [:index, :create]
           resources :likes, only: [:create]
         end
       end
     end
  end

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy]
  end

  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create]
  end
  resources :comments, only: %i[destroy]
  resources :likes, only: %i[destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :create, Post
      can :create, Like

      can :destroy, Post do |post|
        post.author_id == user.id
      end

      can :destroy, Comment do |comment|
        comment.author_id == user.id
      end

      can :destroy, Like do |like|
        like.author_id == user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.size)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_post_counter

  def update_post_counter
    author.update(posts_counter: author.posts.size)
  end

  def recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def recent_posts
    posts.last(3)
  end
end

app/controllers/api/v1/authentication_controller.rb
class Api::V1::AuthenticationController < ApplicationController
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed
  end

  def register_success
    render json: { message: 'Signed up sucessfully.' }
  end

  def register_failed
    render json: { message: 'Something went wrong.' }
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: @comments, status: :ok
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      render json: { status: 201, message: 'Comment creation success!', content: { comment: @comment } }
    else
      render json: @comment.errors, status: :bad_request, message: 'Failed!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render json: @posts, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @user = User.all
    render json: @user, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_with_token
  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def authenticate_with_token
    return unless params[:apitoken]

    user = User.find_by_api_token(params[:apitoken])
    sign_in(user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(text: comment_parameters[:text], author_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to user_post_path(@post.author.id, @post.id), notice: 'Comment created successfully'
        else
          redirect_to user_post_path(@post.author.id, @post.id), alert: 'Comment not created, try again!'
        end
      end
    end
  end

  def destroy
    previous_url = request.env['HTTP_REFERER']
    comment_to_delete = Comment.find(params[:comment_id])

    if comment_to_delete.destroy
      flash[:notice] = 'Comment Deleted successfully!'
    else
      flash[:alert] = 'Unable to delete comment Try again later'
    end
    redirect_to(previous_url)
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(author_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_path(@post.author.id, @post.id), notice: 'Post Liked 👍'
        else
          redirect_to user_post_path(@post.author.id, @post.id), alert: 'Like not added'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource param_method: :post_params

  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments, :likes).find(params[:id])
  end

  def new
    @current = current_user
  end

  def create
    new_post = current_user.posts.build(post_params)

    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to user_post_path(new_post.author_id, new_post.id), notice: 'Post created successfully'
        else
          render :new, alert: 'Post not created. Please try again!'
        end
      end
    end
  end

  def destroy
    @user = current_user
    @post = @user.posts.find(params[:post_id])
    authorize! :destroy, @post
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user.id), notice: 'Post deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def apitoken
    @user = User.find(params[:id])
    render json: @user.apitoken, status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_img(user)
    user.photo.present? ? user.photo : 'https://p.kindpng.com/picc/s/544-5442212_download-free-icon-vectors-male-visio-user-icon.png'
  end
end

app/views/comments/_comment_form.html.erb
<section class="container mt-5 p-2 bio">
  <%= form_with model:[@post, @post.comments.build], method: :post, local: true do |f| %>
    <%= f.label :text, "comment", class: "form-label fs-6" %><br>
    <%= f.text_area :text, size:"50x5", class: "form-control", placeholder: "Write your comment here...", required: true %><br>

    <%= f.submit "Add Comment", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3"%>
  <% end %>
  <%= render "likes/like_form" %>
</section>

app/views/comments/create.html.erb
<section class="container mt-5 p-2 bio">
 <%= render "comment_form" %>
</section>

app/views/layouts/_commcard.html.erb
<% unless @post.comments.empty? %>
<ul class="border border-3 border-dark container p-2 my-5 bio">
  <% @post.comments.each do |comment| %>
  <li class="d-flex justify-content-between zebra p-2" >
    <div>
      <%= comment.author.name %>: <%= comment.text%>
    </div>
    <div>
      <% if can? :destroy, comment %>
      <%= button_to 'Delete Comment', "/posts/:post_id/comments/#{params[:id]}", method: :delete, params: { comment_id: comment.id}, class: "btn btn-danger mb-3" %>
      <% end %>
    </div>
  </li>
  <% end %>
</ul>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success text-center msg"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/_like_form.html.erb
<%= form_with model:[@post, @post.likes.build] do |f|%>
  <%= f.submit "Like this post" , data: {disable_with: "👍"}, class: "btn btn-success mb-3"%>
<%end%>

app/views/likes/create.html.erb
<section>
  <%= render "like_form" %>
</section>

app/views/posts/_create_comments.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comment do |form| %>
<div class="new-comment-area">
	<%= form.text_area :text, placeholder: "Type something here...", rows: 14, required: true %>
	<%= form.submit "Comment", class: "button" %>
  </div>
<% end %>

app/views/posts/_post_form.html.erb
<div class="fs-4 p-3 border border-1 container mt-5 p-2 bio">
  <%= form_with model:[@current, @current.posts.build], method: :post, local: true do |f| %>
    <%= f.label :title, "Title", class: "form-label fs-6" %>
    <%= f.text_field :title, :placeholder => "Add Your title here...", required: true, class: "form-control mb-4" %>

    <%= f.label :text, "Write a new post", class: "form-label fs-6" %>
    <%= f.text_area :text, size: "80x15", :placeholder => "Add your post here...", required: true, class: "form-control" %>

    <%= f.submit "Add Post", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div>
<ul class="nav justify-content-center bg-light text-white">
  <li class="nav-item">
    <%= link_to "Create Post", new_user_post_path(@user.id), class: "nav-link" %>
  </li>
  <li class="nav-item">
     <%= link_to "Home", root_path,  class: "nav-link" %>
  </li>
</ul>
  <%= render partial: "users/user_profile", locals: { user: @user } %>
  <ul>
    <% @user.posts.each do |p| %>
      <li>
        <div class="border border-3 border-dark container mt-5 p-2 bio">
          <%= link_to user_post_path(@user.id, p.id), id: "user_post#{p.id}" do %>
          <h4><%= p.title%></h4>
          <% end %>
          <p><%= p.text%></p>
          <div>
            <span>Comments: <%= p.comments.size %></span>
            <span>Likes: <%= p.comments.size %></span>
          </div>
        </div>
        <div>
          <ul class="border border-3 border-dark container p-2 mt-1 bio">
            <% p.recent_comments.each do |c| %>
            <li><%= c.author.name %>: <%= c.text%></li>
            <% end %>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
  <button class="btn btn-primary d-flex justify-content-center align-self-center my-5 button display">Pagination</button>
</div>

app/views/posts/new.html.erb
<ul class="nav justify-content-center bg-light text-white">
  <li class="nav-item">
    <%= link_to "Back", :back, class: "nav-link" %>
  </li>
</ul>
<h3 class="fs-2 p-3 container mt-2 p-2 bio"> Create Your Post</h3>
<div>
  <%= render "post_form" %>
</div>

app/views/posts/show.html.erb
<nav class="fs-6 p-3 container mt-2 p-2 bio">
  <%= link_to "Home", root_path %>
</nav>
<div>
  <div>
    <div class="border border-3 border-dark container p-2 my-5 bio">
      <div class="d-flex justify-content-between my-3">
        <h4><%= @post.title %> by <%= @user.name %></h4>
        <p>Comments : <%= @post.comments.size%> Likes : <%= @post.likes.size %> </p>

      </div>
      <p><%= @post.text %> </p>
      <% if can? :destroy, @post %>
      <%= button_to 'Delete Comment', "/users/:author_id/posts/#{params[:id]}", method: :delete, params: { post_id: @post.id}, class: "btn btn-danger mb-3" %>
      <% end %>
    </div>

    <%= render "layouts/commcard" %>
    <%= render "comments/comment_form" %>
  </div>
</div>

app/views/users/_user_profile.html.erb
<section>
  <div class="display mt-5">
    <img src=<%= user_img(user) %> alt="User profile picture" id="img-user" class="border border-3 border-dark">
    <div class="user_list border border-3 border-dark d-flex justify-content-between py-5">
      <h2 class="user_name"><%= user.name %></h2>
      <p class="num_post flex-row-reverse fs-6">Number of posts: <%= user.posts.size %></p>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div>
<ul class="nav justify-content-center bg-light text-white">
  <li class="nav-item">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
  </li>
  <li class="nav-item">
   <%= link_to "Settings", edit_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
   <%= link_to "Profile", current_user, class: 'nav-link' %>
  </li>
</ul>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <%= render partial: "user_profile", locals: {user: user} %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
<ul class="nav justify-content-center bg-light text-white">
  <li class="nav-item">
    <%= link_to "Home", root_path, class: "nav-link" %>
  </li>
</ul>
  <%= render partial: "user_profile", locals: {user: @user} %>
  <div class="border border-3 border-dark container p-2 my-5 bio">
    <h3 class="py-4">Bio</h3>
    <p><%= @user.bio %> </p>
  </div>
  <ul>
    <% @user.recent_posts.each do |p| %>
      <li class="border border-3 border-dark container p-2 my-5 bio" >
        <div>
          <div>
            <%= link_to user_post_path(@user.id, p.id), id: "user_post#{p.id}" do %>
              <h4 class="py-4"><%= p.title %></h4>
            <% end %>
            <p><%= p.text %> </p>
          <div>
          <span>Comments: <%= p.comments.size %></span>
          <span>Likes: <%= p.likes.size %></span>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
  <div>
    <%= link_to "See all posts", user_posts_path(@user.id), class: "btn btn-primary d-flex justify-content-center align-self-center mb-5 button display" %>
  <div>
</div>